spring:
  application:
    name: restaurants-service
  datasource:
    url: jdbc:mysql://localhost:3306/dayaeyak
    username: root
    password: sparta1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true

  profiles:
    active: dev

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      write-dates-as-timestamps: false

